
skillMetadata:
  sections:
    - name: Options
      fields:
        - name: list_name
          type: text
          label: Todoist Project Name
          value: "Shopping List"
        - name: todoist_api_key
          type: text
          label: Todoist API Key
          value: ""
          placeholder: demo prompt in the input box
    - name: Login << Name of another section
      fields:
        - type: label
          label: Just a little bit of extra info for the user to understand following settings
        - name: username
          type: text
          label: Username
          value: ""
        - name: password
          type: password
          label: Password
          value: ""
