
skillMetadata:
  sections:
    - name: Options
      fields:
        - name: parent_project_name
          type: text
          label: Todoist Parent Project Name
          value: "Shopping Lists"
        - name: todoist_api_key
          type: text
          label: Todoist API Key
          value: ""